### ISSUE TITLE
"Create a new issue" link is broken in contribution section of the README

### ISSUE THREAD

**Issue by aj-dev** [jvandemo/angularcodereview-com#2]
The link address is [https://github.com/jvandemo/angularcodereview-com/blob/master/issues/new](https://github.com/jvandemo/angularcodereview-com/blob/master/issues/new) when it should be [https://github.com/jvandemo/angularcodereview-com/issues/new](https://github.com/jvandemo/angularcodereview-com/issues/new)

**Comment by jvandemo** [comment]
@aj-dev &mdash; The link has been updated to resolve the issue.

Thank you for reporting! 👍
