### ISSUE TITLE
new entry for angularjs security part - user must not be able to change client side template

### ISSUE THREAD

**Issue by anschnapp** [jvandemo/angularcodereview-com#4]
Check if it's not possible for the user to change client side template

> * Do not mix client and server templates
> * Do not use user input to generate templates dynamically
> * Do not run user input through $scope.$eval (or any of the other expression parsing functions listed above)

Also don't allow user input for expressions used in 
* watches
* eval/evalAsync
* apply/applyAsync
* $compile
* $parse
* interpolate
* used in orderBy pipe

see: https://docs.angularjs.org/guide/security

**Comment by jvandemo** [comment]
@git2snap &mdash; Awesome, would you be interested in creating a PR for this? Thanks! 👍

**Comment by anschnapp** [comment]
Hi @jvandemo, happy that you like it! Sure I will make a PR for this.

**Comment by jvandemo** [comment]
@git2snap &mdash; Thank you, much appreciated!

**Comment by anschnapp** [comment]
Hi @jvandemo, i have added a PR some time ago. The build failed but for me it looks like the problem is not related to my changes (maybe some misconfiguration in the pipe?). 

Please inform me if the issue is on my side.

**Comment by jvandemo** [comment]
@git2snap &mdash; The JSPM auth token had expired. I have updated it and now your changes have been deployed to the website.

Thanks again for your wonderful addition. Much appreciated! 🏆
